# PIPELINE DEFINITION
# Name: train-model
# Inputs:
#    processed_data: system.Dataset
# Outputs:
#    model_output: system.Model
components:
  comp-train-model:
    executorLabel: exec-train-model
    inputDefinitions:
      artifacts:
        processed_data:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
    outputDefinitions:
      artifacts:
        model_output:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-train-model:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - train_model
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.15.1'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef train_model(processed_data: Input[Dataset], model_output: Output[Model]):\n\
          \    \"\"\"\n    Train Random Forest on processed data.\n    \"\"\"\n  \
          \  df = pd.read_csv(processed_data.path)\n\n    X_train = df.drop(\"label\"\
          , axis=1)\n    y_train = df[\"label\"]\n\n    model = RandomForestRegressor(n_estimators=50,\
          \ random_state=42)\n    model.fit(X_train, y_train)\n\n    joblib.dump(model,\
          \ model_output.path)\n\n"
        image: python:3.11
pipelineInfo:
  name: train-model
root:
  dag:
    outputs:
      artifacts:
        model_output:
          artifactSelectors:
          - outputArtifactKey: model_output
            producerSubtask: train-model
    tasks:
      train-model:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train-model
        inputs:
          artifacts:
            processed_data:
              componentInputArtifact: processed_data
        taskInfo:
          name: train-model
  inputDefinitions:
    artifacts:
      processed_data:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
  outputDefinitions:
    artifacts:
      model_output:
        artifactType:
          schemaTitle: system.Model
          schemaVersion: 0.0.1
schemaVersion: 2.1.0
sdkVersion: kfp-2.15.1
